<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latestmajor</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>HuffmanAlgorithm</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Structures\Structures.csproj"/>
    </ItemGroup>

</Project>
